language: perl

perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
   - 5.12
   - 5.10

before_install:
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 SKIP_POD_LINKCHECK=1

install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Dist::Zilla::Plugin::PodWeaver Pod::Coverage::Moose Pod::Weaver::Section::Contributors Test::Spelling
   - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps --missing  | cpanm --verbose"

script:
   - dzil test --all

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
