language: perl
perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
   - 5.12
   - 5.10
before_install:
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Pod::Weaver::Section::Contributors
   - "dzil authordeps | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied"
   - "dzil listdeps   | cpanm --verbose --skip-satisfied"
script:
   - dzil smoke --release --author
